### ISSUE TITLE
Missing Flux loops & APIs

### ISSUE THREAD

**Issue by wolverdude** [bcai/Instant-Noodle#2]
I don't see any flux loops or APIs for:
- `collections`
- `comments`
- `likes`

Are these entirely nested inside `posts`? If so, how are these objects created? What are the APIs and flux loops for that?

Be sure to make a note of whatever data is nested in APIs.

**Comment by bcai** [comment]
I'm definitely confused about how many different stores I might have to create. I know I need a PostStore, but since Comments and Likes are nested subcomponents, I didn't know whether those need to be their own distinct stores as well. Was thinking maybe we could take some time to talk about this issue in person.

**Comment by bcai** [comment]
Updated API and Flux Loops to include "comments" and "likes".
